#pragma once
int USERNAME_MIN_LENGTH = 3;
int USERNAME_MAX_LENGTH = 20;
int PHONE_NUMBER_MIN_LENGTH = 11;
int PHONE_NUMBER_MAX_LENGTH = 12;
int NAME_MIN_LENGTH = 3;
int NAME_MAX_LENGTH = 20;
int PASSWORD_MIN_LENGTH = 8;
int PASSWORD_MAX_LENGTH = 64;