#pragma once
int USERNAME_MIN_LENTH = 3;
int USERNAME_MAX_LENTH = 20;
int PHONE_NUMBER_MIN_LENTH = 11;
int PHONE_NUMBER_MAX_LENTH = 12;
int NAME_MIN_LENTH = 3;
int NAME_MAX_LENTH = 10;
int PASSWORD_LENTH = 8;